// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package organizationpermission

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// Create creates a new organization permission.
func Create(ctx context.Context, params *CreateParams) (*clerk.OrganizationPermission, error) {
	return getClient().Create(ctx, params)
}

// Get retrieves details for an organization permission.
func Get(ctx context.Context, permissionID string) (*clerk.OrganizationPermission, error) {
	return getClient().Get(ctx, permissionID)
}

// Update updates an organization permission.
func Update(ctx context.Context, permissionID string, params *UpdateParams) (*clerk.OrganizationPermission, error) {
	return getClient().Update(ctx, permissionID, params)
}

// Delete removes an organization permission.
func Delete(ctx context.Context, permissionID string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, permissionID)
}

// List returns a list of organization permissions.
func List(ctx context.Context, params *ListParams) (*clerk.OrganizationPermissionList, error) {
	return getClient().List(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
