// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
// Last generated at 2024-02-07 13:46:28.207158003 +0000 UTC
package client

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Get retrieves the client specified by ID.
func Get(ctx context.Context, id string) (*clerk.Client, error) {
	return getClient().Get(ctx, id)
}

// Verify verifies the Client in the provided JWT.
func Verify(ctx context.Context, params *VerifyParams) (*clerk.Client, error) {
	return getClient().Verify(ctx, params)
}

// List returns a list of all the clients.//// Deprecated: The operation is deprecated and will be removed in// future versions.
func List(ctx context.Context, params *ListParams) (*clerk.ClientList, error) {
	return getClient().List(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
