// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package audit_logs

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// List returns a list of audit logs.
func List(ctx context.Context, params *ListParams) (*clerk.AuditLogList, error) {
	return getClient().List(ctx, params)
}

// Get retrieves a single audit log by its composite key.
func Get(ctx context.Context, params *GetParams) (*clerk.AuditLogWithPayload, error) {
	return getClient().Get(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
