// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package organizationdomain

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Create adds a new domain to the organization.
func Create(ctx context.Context, organizationID string, params *CreateParams) (*clerk.OrganizationDomain, error) {
	return getClient().Create(ctx, organizationID, params)
}

// Update updates an organization domain.
func Update(ctx context.Context, organizationID, domainID string, params *UpdateParams) (*clerk.OrganizationDomain, error) {
	return getClient().Update(ctx, organizationID, domainID, params)
}

// Delete removes a domain from an organization.
func Delete(ctx context.Context, params *DeleteParams) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, params)
}

// List returns a list of organization domains.
func List(ctx context.Context, organizationID string, params *ListParams) (*clerk.OrganizationDomainList, error) {
	return getClient().List(ctx, organizationID, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
