// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package email

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// Send sends a transactional email.
func Send(ctx context.Context, params *SendParams) (*clerk.Email, error) {
	return getClient().Send(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
