// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package email

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// Send sends a transactional email.
//
// Experimental: This method calls an internal, not-yet-public endpoint and is
// subject to change. It is advised to pin the SDK version to avoid breaking
// changes. See https://clerk.com/docs/pinning.
func Send(ctx context.Context, params *SendParams) (*clerk.Email, error) {
	return getClient().Send(ctx, params)
}

// Get returns Clerk's stored provider-acceptance state for a transactional
// email. An accepted status does not prove final delivery.
func Get(ctx context.Context, emailID string) (*clerk.Email, error) {
	return getClient().Get(ctx, emailID)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
