// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package directorygrouprolemapping

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// List returns all group role mappings for a directory.
func List(ctx context.Context, directoryID string) (*clerk.DirectoryGroupRoleMappingList, error) {
	return getClient().List(ctx, directoryID)
}

// ListGroups returns directory groups for a directory with cursor pagination.
func ListGroups(ctx context.Context, directoryID string, params *ListGroupsParams) (*clerk.DirectoryGroupList, error) {
	return getClient().ListGroups(ctx, directoryID, params)
}

// Create creates a new group role mapping.
func Create(ctx context.Context, directoryID string, params *CreateParams) (*clerk.DirectoryGroupRoleMapping, error) {
	return getClient().Create(ctx, directoryID, params)
}

// BulkUpdate updates multiple group role mappings at once.
// The array position determines precedence (1-indexed).
// All mappings in the directory must be included.
func BulkUpdate(ctx context.Context, directoryID string, params *BulkUpdateParams) (*clerk.DirectoryGroupRoleMappingList, error) {
	return getClient().BulkUpdate(ctx, directoryID, params)
}

// Delete deletes a group role mapping.
func Delete(ctx context.Context, directoryID, mappingID string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, directoryID, mappingID)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
