// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package apikey

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// Create creates a new API key.
func Create(ctx context.Context, params *CreateParams) (*clerk.APIKeyWithSecret, error) {
	return getClient().Create(ctx, params)
}

// Get returns an API key
func Get(ctx context.Context, apiKeyID string) (*clerk.APIKey, error) {
	return getClient().Get(ctx, apiKeyID)
}

// List returns a list of API keys.
func List(ctx context.Context, params *ListParams) (*clerk.APIKeyList, error) {
	return getClient().List(ctx, params)
}

// GetSecret retrieves the secret for an API key.
func GetSecret(ctx context.Context, apiKeyID string) (*APIKeySecret, error) {
	return getClient().GetSecret(ctx, apiKeyID)
}

// Update updates an API key.
func Update(ctx context.Context, apiKeyID string, params *UpdateParams) (*clerk.APIKey, error) {
	return getClient().Update(ctx, apiKeyID, params)
}

// Delete deletes an API key
func Delete(ctx context.Context, apiKeyID string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, apiKeyID)
}

// Revoke revokes an API key.
func Revoke(ctx context.Context, apiKeyID string, params *RevokeParams) (*clerk.APIKey, error) {
	return getClient().Revoke(ctx, apiKeyID, params)
}

// Verify verifies an API key.
func Verify(ctx context.Context, params *VerifyParams) (*clerk.APIKey, error) {
	return getClient().Verify(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
