// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oauthapplication

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Get fetches a single OAuth application by its ID.
func Get(ctx context.Context, id string) (*clerk.OAuthApplication, error) {
	return getClient().Get(ctx, id)
}

// List retrieves all OAuth applications.
func List(ctx context.Context, params *ListParams) (*clerk.OAuthApplicationList, error) {
	return getClient().List(ctx, params)
}

// Create creates a new OAuth application with the given parameters.
func Create(ctx context.Context, params *CreateParams) (*clerk.OAuthApplication, error) {
	return getClient().Create(ctx, params)
}

// Update updates an existing OAuth application.
func Update(ctx context.Context, id string, params *UpdateParams) (*clerk.OAuthApplication, error) {
	return getClient().Update(ctx, id, params)
}

// Delete deletes the given OAuth application
func DeleteOAuthApplication(ctx context.Context, id string) (*clerk.DeletedResource, error) {
	return getClient().DeleteOAuthApplication(ctx, id)
}

// RotateClientSecret rotates the OAuth application's client secret
func RotateClientSecret(ctx context.Context, id string) (*clerk.OAuthApplication, error) {
	return getClient().RotateClientSecret(ctx, id)
}

// RevokeToken revokes an OAuth application's access token or refresh token.
func RevokeToken(ctx context.Context, id string, params *RevokeTokenParams) error {
	return getClient().RevokeToken(ctx, id, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
