// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package scimgrouprolemapping

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// List returns all group role mappings for a SCIM directory.
func List(ctx context.Context, scimDirectoryID string) (*clerk.SCIMGroupRoleMappingList, error) {
	return getClient().List(ctx, scimDirectoryID)
}

// ListGroups returns SCIM groups for a directory with cursor pagination.
func ListGroups(ctx context.Context, scimDirectoryID string, params *ListGroupsParams) (*clerk.SCIMGroupList, error) {
	return getClient().ListGroups(ctx, scimDirectoryID, params)
}

// Create creates a new group role mapping.
func Create(ctx context.Context, scimDirectoryID string, params *CreateParams) (*clerk.SCIMGroupRoleMapping, error) {
	return getClient().Create(ctx, scimDirectoryID, params)
}

// BulkUpdate updates multiple group role mappings at once.
// The array position determines precedence (1-indexed).
// All mappings in the directory must be included.
func BulkUpdate(ctx context.Context, scimDirectoryID string, params *BulkUpdateParams) (*clerk.SCIMGroupRoleMappingList, error) {
	return getClient().BulkUpdate(ctx, scimDirectoryID, params)
}

// Delete deletes a group role mapping.
func Delete(ctx context.Context, scimDirectoryID, mappingID string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, scimDirectoryID, mappingID)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
