// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package testingtoken

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Create creates a new testing token.
func Create(ctx context.Context) (*clerk.TestingToken, error) {
	return getClient().Create(ctx)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
