// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package phonenumber

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// Create creates a new phone number.
func Create(ctx context.Context, params *CreateParams) (*clerk.PhoneNumber, error) {
	return getClient().Create(ctx, params)
}

// Get retrieves a phone number.
func Get(ctx context.Context, id string) (*clerk.PhoneNumber, error) {
	return getClient().Get(ctx, id)
}

// Update updates the phone number specified by id.
func Update(ctx context.Context, id string, params *UpdateParams) (*clerk.PhoneNumber, error) {
	return getClient().Update(ctx, id, params)
}

// ReplaceForUser replaces all of the user's phone numbers with a single
// verified, primary phone number. The new phone number is created with the
// admin verification strategy and is not reserved for second factor. Any
// existing phone numbers are deleted; replacing a phone number that is reserved
// for second factor disables the user's MFA.
func ReplaceForUser(ctx context.Context, params *ReplaceForUserParams) (*clerk.PhoneNumber, error) {
	return getClient().ReplaceForUser(ctx, params)
}

// Delete deletes a phone number.
func Delete(ctx context.Context, id string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, id)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
