// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package directory

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// Create creates a new directory.
func Create(ctx context.Context, params *CreateParams) (*clerk.Directory, error) {
	return getClient().Create(ctx, params)
}

// Get returns details about a directory.
func Get(ctx context.Context, id string) (*clerk.Directory, error) {
	return getClient().Get(ctx, id)
}

// Update updates a directory.
func Update(ctx context.Context, id string, params *UpdateParams) (*clerk.Directory, error) {
	return getClient().Update(ctx, id, params)
}

// List returns a paginated list of directories.
func List(ctx context.Context, params *ListParams) (*clerk.DirectoryList, error) {
	return getClient().List(ctx, params)
}

// Delete deletes a directory.
func Delete(ctx context.Context, id string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, id)
}

// RotateAPIKey rotates the API key for a directory.
// The old API key will be valid for a grace period before expiring.
func RotateAPIKey(ctx context.Context, id string) (*clerk.Directory, error) {
	return getClient().RotateAPIKey(ctx, id)
}

// AddCredentials adds pull-provider credentials (e.g. a Google service-account
// key and subject email) for a directory. They are validated and sealed
// server-side; on success the directory is enabled.
func AddCredentials(ctx context.Context, id string, params *CredentialsParams) (*clerk.Directory, error) {
	return getClient().AddCredentials(ctx, id, params)
}

// Sync enqueues a sync run for a pull-based directory.
func Sync(ctx context.Context, id string) error {
	return getClient().Sync(ctx, id)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
