// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package m2m_token

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Create creates a new M2M token.
func Create(ctx context.Context, params *CreateParams) (*clerk.M2MTokenWithToken, error) {
	return getClient().Create(ctx, params)
}

// List returns a list of M2M tokens.
func List(ctx context.Context, params *ListParams) (*clerk.M2MTokenList, error) {
	return getClient().List(ctx, params)
}

// Revoke revokes an M2M token.
func Revoke(ctx context.Context, tokenID string, params *RevokeParams) (*clerk.M2MToken, error) {
	return getClient().Revoke(ctx, tokenID, params)
}

// Verify verifies an M2M token.
func Verify(ctx context.Context, params *VerifyParams) (*clerk.M2MToken, error) {
	return getClient().Verify(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
