// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package enterpriseconnection

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// Create creates a new enterprise connection.
func Create(ctx context.Context, params *CreateParams) (*clerk.EnterpriseConnection, error) {
	return getClient().Create(ctx, params)
}

// Get returns an enterprise connection by ID.
func Get(ctx context.Context, id string) (*clerk.EnterpriseConnection, error) {
	return getClient().Get(ctx, id)
}

// Update updates an enterprise connection by ID.
func Update(ctx context.Context, id string, params *UpdateParams) (*clerk.EnterpriseConnection, error) {
	return getClient().Update(ctx, id, params)
}

// Delete deletes an enterprise connection.
func Delete(ctx context.Context, id string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, id)
}

// List returns a list of enterprise connections.
func List(ctx context.Context, params *ListParams) (*clerk.EnterpriseConnectionList, error) {
	return getClient().List(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
