// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
// Last generated at 2024-02-06 13:00:05.055482292 +0000 UTC
package domain

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Create creates a new domain.
func Create(ctx context.Context, params *CreateParams) (*clerk.Domain, error) {
	return getClient().Create(ctx, params)
}

// Update updates a domain's properties.
func Update(ctx context.Context, id string, params *UpdateParams) (*clerk.Domain, error) {
	return getClient().Update(ctx, id, params)
}

// Delete removes a domain.
func Delete(ctx context.Context, id string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, id)
}

// List returns a list of domains.
func List(ctx context.Context, params *ListParams) (*clerk.DomainList, error) {
	return getClient().List(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
