// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package admin_portal_link_token

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// Create mints a new admin portal link token. The returned token is shown
// once and must be embedded in the URL delivered to the IT contact.
func Create(ctx context.Context, params *CreateParams) (*clerk.AdminPortalLinkTokenWithToken, error) {
	return getClient().Create(ctx, params)
}

// Revoke revokes an admin portal link token.
func Revoke(ctx context.Context, adminPortalLinkTokenID string, params *RevokeParams) (*clerk.AdminPortalLinkToken, error) {
	return getClient().Revoke(ctx, adminPortalLinkTokenID, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
