// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
// Last generated at 2024-02-08 13:48:28.874404424 +0000 UTC
package proxycheck

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Create creates a proxy check.
func Create(ctx context.Context, params *CreateParams) (*clerk.ProxyCheck, error) {
	return getClient().Create(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
