// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package proxycheck

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Create creates a proxy check.
//
// Deprecated: The operation is deprecated and will be removed in
// future versions.
func Create(ctx context.Context, params *CreateParams) (*clerk.ProxyCheck, error) {
	return getClient().Create(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
