// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package jwks

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Get retrieves a JSON Web Key set.
func Get(ctx context.Context, params *GetParams) (*clerk.JSONWebKeySet, error) {
	return getClient().Get(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
