// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package organizationinvitation

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Create creates and sends an invitation to join an organization.
func Create(ctx context.Context, params *CreateParams) (*clerk.OrganizationInvitation, error) {
	return getClient().Create(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
