// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package logs

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// Get retrieves a single log by its composite key (event_time_ms:event_id).
// Unlike List, the returned object includes the full event payload.
func Get(ctx context.Context, params *GetParams) (*clerk.LogWithPayload, error) {
	return getClient().Get(ctx, params)
}

// List returns a list of logs.
func List(ctx context.Context, params *ListParams) (*clerk.LogList, error) {
	return getClient().List(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
