// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package machinescope

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// CreateScope creates a new machine scope.
func CreateScope(ctx context.Context, machineID string, params *CreateScopeParams) (*clerk.MachineScope, error) {
	return getClient().CreateScope(ctx, machineID, params)
}

// DeleteScope deletes a machine scope.
func DeleteScope(ctx context.Context, machineID string, otherMachineID string) (*clerk.DeletedMachineScope, error) {
	return getClient().DeleteScope(ctx, machineID, otherMachineID)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
