// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
// Last generated at 2024-02-08 11:11:11.25429 +0000 UTC
package redirecturl

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Create creates a new redirect url.
func Create(ctx context.Context, params *CreateParams) (*clerk.RedirectURL, error) {
	return getClient().Create(ctx, params)
}

// Get retrieves details for a redirect url by ID.
func Get(ctx context.Context, id string) (*clerk.RedirectURL, error) {
	return getClient().Get(ctx, id)
}

// Delete deletes a redirect url.
func Delete(ctx context.Context, id string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, id)
}

// List returns a list of redirect urls.
func List(ctx context.Context, params *ListParams) (*clerk.RedirectURLList, error) {
	return getClient().List(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
