// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
// Last generated at 2024-02-08 13:01:58.273814248 +0000 UTC
package organizationmembership

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Create adds a new member to the organization.
func Create(ctx context.Context, params *CreateParams) (*clerk.OrganizationMembership, error) {
	return getClient().Create(ctx, params)
}

// Update updates an organization membership.
func Update(ctx context.Context, params *UpdateParams) (*clerk.OrganizationMembership, error) {
	return getClient().Update(ctx, params)
}

// Delete removes a member from an organization.
func Delete(ctx context.Context, params *DeleteParams) (*clerk.OrganizationMembership, error) {
	return getClient().Delete(ctx, params)
}

// List returns a list of organization memberships.
func List(ctx context.Context, params *ListParams) (*clerk.OrganizationMembershipList, error) {
	return getClient().List(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
