// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package organizationrole

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Create creates a new organization role.
func Create(ctx context.Context, params *CreateParams) (*clerk.OrganizationRole, error) {
	return getClient().Create(ctx, params)
}

// Get retrieves details for an organization role.
func Get(ctx context.Context, roleID string) (*clerk.OrganizationRole, error) {
	return getClient().Get(ctx, roleID)
}

// Update updates an organization role.
func Update(ctx context.Context, roleID string, params *UpdateParams) (*clerk.OrganizationRole, error) {
	return getClient().Update(ctx, roleID, params)
}

// Delete removes an organization role.
func Delete(ctx context.Context, roleID string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, roleID)
}

// List returns a list of organization roles.
func List(ctx context.Context, params *ListParams) (*clerk.OrganizationRoleList, error) {
	return getClient().List(ctx, params)
}

// AssignPermission assigns a permission to an organization role.
func AssignPermission(ctx context.Context, roleID, permissionID string) (*clerk.OrganizationRole, error) {
	return getClient().AssignPermission(ctx, roleID, permissionID)
}

// RemovePermission removes a permission from an organization role.
func RemovePermission(ctx context.Context, roleID, permissionID string) (*clerk.OrganizationRole, error) {
	return getClient().RemovePermission(ctx, roleID, permissionID)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
