// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package scimdirectory

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// Create creates a new SCIM directory.
func Create(ctx context.Context, params *CreateParams) (*clerk.SCIMDirectory, error) {
	return getClient().Create(ctx, params)
}

// Get returns details about a SCIM directory.
func Get(ctx context.Context, id string) (*clerk.SCIMDirectory, error) {
	return getClient().Get(ctx, id)
}

// Update updates a SCIM directory.
func Update(ctx context.Context, id string, params *UpdateParams) (*clerk.SCIMDirectory, error) {
	return getClient().Update(ctx, id, params)
}

// List returns a paginated list of SCIM directories.
func List(ctx context.Context, params *ListParams) (*clerk.SCIMDirectoryList, error) {
	return getClient().List(ctx, params)
}

// Delete deletes a SCIM directory.
func Delete(ctx context.Context, id string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, id)
}

// RotateAPIKey rotates the API key for a SCIM directory.
// The old API key will be valid for a grace period before expiring.
func RotateAPIKey(ctx context.Context, id string) (*clerk.SCIMDirectory, error) {
	return getClient().RotateAPIKey(ctx, id)
}

// Credentials uploads pull-provider credentials (e.g. a Google service-account
// key and subject email) for a SCIM directory. They are validated and sealed
// server-side; on success the directory is enabled.
func Credentials(ctx context.Context, id string, params *CredentialsParams) (*clerk.SCIMDirectory, error) {
	return getClient().Credentials(ctx, id, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
