// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package waitlistentry

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// List returns all waitlist entries.
func List(ctx context.Context, params *ListParams) (*clerk.WaitlistEntriesList, error) {
	return getClient().List(ctx, params)
}

// Create adds a new waitlist entry.
func Create(ctx context.Context, params *CreateParams) (*clerk.WaitlistEntry, error) {
	return getClient().Create(ctx, params)
}

// Invite accepts a waitlist entry
func Invite(ctx context.Context, id string, params *InviteParams) (*clerk.WaitlistEntry, error) {
	return getClient().Invite(ctx, id, params)
}

// Reject denies a waitlist entry
func Reject(ctx context.Context, id string) (*clerk.WaitlistEntry, error) {
	return getClient().Reject(ctx, id)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
