// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package machine

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// Create creates a new machine.
func Create(ctx context.Context, params *CreateParams) (*clerk.MachineWithScopedMachinesAndSecretKey, error) {
	return getClient().Create(ctx, params)
}

// Get retrieves details for a machine.
func Get(ctx context.Context, id string) (*clerk.MachineWithScopedMachines, error) {
	return getClient().Get(ctx, id)
}

func GetSecretKey(ctx context.Context, id string) (*clerk.MachineSecretKey, error) {
	return getClient().GetSecretKey(ctx, id)
}

// Update updates a machine.
func Update(ctx context.Context, id string, params *UpdateParams) (*clerk.MachineWithScopedMachines, error) {
	return getClient().Update(ctx, id, params)
}

// Delete deletes a machine.
func Delete(ctx context.Context, id string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, id)
}

// List returns a list of machines.
func List(ctx context.Context, params *ListParams) (*clerk.MachineList, error) {
	return getClient().List(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
