// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package emailaddress

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v3"
)

// Create creates a new email address.
func Create(ctx context.Context, params *CreateParams) (*clerk.EmailAddress, error) {
	return getClient().Create(ctx, params)
}

// Get retrieves an email address.
func Get(ctx context.Context, id string) (*clerk.EmailAddress, error) {
	return getClient().Get(ctx, id)
}

// Update updates the email address specified by id.
func Update(ctx context.Context, id string, params *UpdateParams) (*clerk.EmailAddress, error) {
	return getClient().Update(ctx, id, params)
}

// ReplaceForUser replaces all of the user's email addresses with a single
// verified, primary email address. The new email address is created with the
// admin verification strategy and any existing email addresses are deleted. If
// an existing email address is linked to a connected account, the request is
// rejected; remove the connected account first.
func ReplaceForUser(ctx context.Context, params *ReplaceForUserParams) (*clerk.EmailAddress, error) {
	return getClient().ReplaceForUser(ctx, params)
}

// Delete deletes an email address.
func Delete(ctx context.Context, id string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, id)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
