// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package emailaddress

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Create creates a new email address.
func Create(ctx context.Context, params *CreateParams) (*clerk.EmailAddress, error) {
	return getClient().Create(ctx, params)
}

// Get retrieves an email address.
func Get(ctx context.Context, id string) (*clerk.EmailAddress, error) {
	return getClient().Get(ctx, id)
}

// Update updates the email address specified by id.
func Update(ctx context.Context, id string, params *UpdateParams) (*clerk.EmailAddress, error) {
	return getClient().Update(ctx, id, params)
}

// Delete deletes an email address.
func Delete(ctx context.Context, id string) (*clerk.DeletedResource, error) {
	return getClient().Delete(ctx, id)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
