// Code generated by "gen"; DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
// Last generated at 2024-02-08 13:35:10.578898463 +0000 UTC
package session

import (
	"context"

	"github.com/clerk/clerk-sdk-go/v2"
)

// Get retrieves details for a session.
func Get(ctx context.Context, id string) (*clerk.Session, error) {
	return getClient().Get(ctx, id)
}

// List returns a list of sessions.
func List(ctx context.Context, params *ListParams) (*clerk.SessionList, error) {
	return getClient().List(ctx, params)
}

// Revoke marks the session as revoked.
func Revoke(ctx context.Context, params *RevokeParams) (*clerk.Session, error) {
	return getClient().Revoke(ctx, params)
}

// Verify verifies the session.
//
// Deprecated: The operation is deprecated and will be removed in future versions.
// It is recommended to switch to networkless verification using short-lived
// session tokens instead.
// See https://clerk.com/docs/backend-requests/resources/session-tokens
func Verify(ctx context.Context, params *VerifyParams) (*clerk.Session, error) {
	return getClient().Verify(ctx, params)
}

func getClient() *Client {
	return &Client{
		Backend: clerk.GetBackend(),
	}
}
